# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  gitrepo:
    description: 'repository name'
    required: true
  registryname:
    description: 'registry hostname'
    required: true
  registryuser:
    description: 'registry user / actor'
    required: true
  registrytoken:
    description: 'registry token / password'
    required: true
  gitref:
    description: 'git ref to create the image tag'
    required: true
  imagename:
    description: 'container image name'
    required: true
  dockerfile:
    description: 'Dockerfile name - optional - default is Dockerfile'
    required: false
  buildcontext:
    description: 'Context for Docker build - optional - default is .'
    required: false
  buildarg:
    description: 'Contents of --build-arg parameter passed to Docker build - optional - default is empty string'
    required: false
outputs:
  image:
    description: 'image url on registry'
  tag:
    description: 'tag of image'
runs:
  using: 'docker'
  image: 'Dockerfile'
